apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-k8s-proxy
  name: oauth2-k8s-proxy
  namespace: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-k8s-proxy
  template:
    metadata:
      labels:
        app: oauth2-k8s-proxy
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: oauth2-k8s-proxy
        image: djkormo/oauth2-k8s-proxy:main
        name: oauth2-k8s-proxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: proxy
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"  

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true

      restartPolicy: Always  
  
