apiVersion: v1
kind: Service
metadata:
  name: oauth2-k8s-proxy
  namespace: proxy
spec:
  ports:
  - name: oauth2-k8s-proxy
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: oauth2-k8s-proxy
  type: ClusterIP
